id: IFAE3113E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T09:48:31+00:00'
last_modified: '2022-06-10T05:22:47.757374+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC289
  title: ཐུའུ་བཀྭན་བློ་བཟང་ཆོས་ཀྱི་ཉི་མའི་གསུང་མགུར་བསླབ་བྱ་དང་ཆབ་ཤོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CCBC:
      image_group_id: I2PD18301
      title: Volume 1 of thu'u bkwan blo bzang chos kyi nyi ma'i gsung mgur bslab
        bya dang chab shog
      total_pages: 330
      order: 1
      base_file: CCBC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
